### ISSUE TITLE
gRPC connection should be a singleton

### ISSUE THREAD

**Issue by kkweon** [codingpot/pr12er#10]
Instead of connecting every time, the connection should be maintained in a singleton state.

**Comment by deep-diver** [comment]
참고자료
- `Dart`의 `factory` 키워드 (factory constructor)
- https://stackoverflow.com/questions/12649573/how-do-you-build-a-singleton-in-dart
- https://stackoverflow.com/questions/11112506/what-are-the-semantics-of-internal

**Comment by kkweon** [comment]
Fixed in #17
