### ISSUE TITLE
Implement GetVideos

### ISSUE THREAD

**Issue by kkweon** [codingpot/pr12er#19]
```proto
service Pr12erService {
  rpc GetVideos(GetVideosRequest) returns (GetVideosResponse); // <-- this
}
```

**Comment by nicewook** [comment]
서버에서 이 요청을 받으면 정확히 어떤걸 해줘야 하나요? 
예를 들어 youtube 에서 제공하는 api에서 어떤 내용을 받아서 전달해준다?

**Comment by kkweon** [comment]
> 서버에서 이 요청을 받으면 정확히 어떤걸 해줘야 하나요?

GetVideosResponse를 채워서 모든 비디오를 보내는걸로 되어있는데
PR 양이 좀 많기 때문에 Pagination이 필요할 수도 있을 것 같네요.  
그러면 Request 하는 부분도 변경되어야 되겠네요. 일단 지금은 전체만 돌린다고 생각하시면 될 것 같습니다 (cc: @deep-diver)


> 예를 들어 youtube 에서 제공하는 api에서 어떤 내용을 받아서 전달해준다?

구현은 구현하는 사람이 알아서 잘~ 하는걸로 되있습니다 껄껄껄.

- 메타데이터 덤프: https://raw.githubusercontent.com/codingpot/pr12er/main/server/internal/pr12_metadata.pbtxt
- 플레이리스트: https://www.youtube.com/playlist?list=PLzTCYDT_gsddESLSohQ8HWzBvAUttaiR6&jct=d9dX7g1cZCJqdoi85MENqZ7shj9AbQ
- paperswithcode go 구현체까지 https://pkg.go.dev/github.com/codingpot/paperswithcode-go/v2

제 생각엔 이정도면 모든 경우는 아니더라도 대부분 채울 수 있을 것 같습니다.

**Comment by deep-diver** [comment]
변경된다면, `prev`, `next` 와 같은 필드가 추가되면 되겠군요. 또는 `page_number` 같은?

**Comment by nicewook** [comment]
경모님 예전 작업 참고
* 코드: https://github.com/kkweon/pr12/blob/master/utils/read_youtube.py
* 덤프: https://github.com/kkweon/pr12/blob/master/data.yaml

**Comment by nicewook** [comment]
추출해 낼 수 있는게 
- youtube link
- publish 날짜
- title에서: pr 번호, 논문 제목 정도로 보입니다.

고민인게 다음내용 정도네요. 
1. 발표자를 추출하기 어렵다 (일관된 포맷이 아님)
2. 발표자 이름이 포함된 title도 있다.

**Comment by nicewook** [comment]
헷갈리는 부분
반복적으로 YouTube API (+paperswithcode)를 이용해서 데이터를 업데이트 하여 pbtxt로 저장해주고 이걸로 서빙하는 것이지요?

1. keyword 들은 어디서 추출하는 것인가요?
2. PaperMetadata, VideoMetadata는 배열일 이유가 있는 것인가요? 여러 개인 발표가 있는 것인지, 아니면 미래 확장성 때문인지

**Comment by kkweon** [comment]
![image](https://user-images.githubusercontent.com/2981167/120835675-7a33c700-c519-11eb-8072-50b55a06a31d.png)

1. best available sources (기존 메타데이터, paperwith code, 사람 판단)
2. 필요하다면 수정하셔도 됩니다. PR ID 하나당 페이퍼는 1:(1,N)관계입니다. 비디오는 1:1 이었던것 같으니 수정하셔도 됩니다.

**Comment by kkweon** [comment]
절대 한번에 구현보다는 테스트 튼튼한 스몰 PR을 기억해주시길

**Comment by nicewook** [comment]
넵~ 경모님이 공유주신 pbtxt는 어떻게 작성하신 건가요? 다른 분이 깃헙에 정리주신것에서 추출하신건 아닌가 싶기도 한데 
- 키워드
- 제목에 발표자 이름이 들어가 있는 비디오가 있는데 그것도 바로 표기된 것 같아서요

**Comment by kkweon** [comment]
그 리포에서 단발로 추출한게 맞습니다.

**Comment by nicewook** [comment]
metadataDump로 추출해서 파일로 떨구는 것 까지는 가능하겠습니다. 따로 고루틴 돌려서 주기적으로 받아놓게 하면 될것 같습니다. 더 좋은 아이디어가 있을까요?
키워드는 수작업, 와 유튜브 영상 제목 컨벤션 문제는 문제 있는 녀석들만 예외처리 해야하나 싶네요.

**Comment by kkweon** [comment]
애플리케이션 로직을 섞는게 아닌 여러 바이너리 다 각자 하나의 일만 하도록 해주셨으면 좋겠지만 원래 의도는 최대한 백엔드 하는 사람이 자유롭게 하도록 하는 거였기 때문에 

그래도 첫 시작은 그것보다는 현재 있는걸로 조합해서 리턴하는 것부터 하는게 좋을 것 같습니다. 이미 PR 200여가지 메타데이터가 있으니까요.

**Comment by nicewook** [comment]
넵
1. 일단은 경모님이 추출해놓은 pr12_metadata.pbtxt 를 이용해 서빙하도록 한다
2. dumper - 이해했습니다

**Comment by kkweon** [comment]
그래도 재미로 하는거니 필요에 의한것보다 하고 싶으신거 먼저 하셔도 됩니다😄

**Comment by nicewook** [comment]
이것도 재미있습니다 하하
여기에 유튜브 조회수나 좋아요, 페이퍼 스타수를 추가해보는걸 고민해보겠습니다. :-)
