### ISSUE TITLE
클라이언트 코드 in Flutter scaffolding

### ISSUE THREAD

**Issue by kkweon** [codingpot/pr12er#2]
# Expectation

1. 앱이 켜지면 input field 와 send 버튼이 보임
2. input field 와 send 버튼을 누르면 `GetHelloRequest` 프로토를 만들어서 `GetHello(GetHelloRequest)` 를 호출
3. `GetHelloResponse` 프로토를 받아서 화면에 출력

**Comment by deep-diver** [comment]
참고자료
https://towardsdev.com/flutter-grpc-9c6029662dcc

**Comment by kkweon** [comment]
일단 프로토콜버퍼 없이 대충 화면만 나오는 client 디렉토리에 프로젝트 생성해주시면 될듯해요.
