### ISSUE TITLE
add Detail View when clicking an item from ListView

### ISSUE THREAD

**Issue by deep-diver** [codingpot/pr12er#33]
Detail View can contain multiple information.
For this issue, I want to propose a detail view with only YouTube video player located on the top.

![Screen Shot 2021-05-30 at 10 34 22 PM](https://user-images.githubusercontent.com/26025527/120106224-3c404700-c197-11eb-9c0c-5ab8d681c2f8.png)

**Comment by kkweon** [comment]
This is implemented in #35
