### ISSUE TITLE
Presenter 영문 <--> 한글 이름 Dictionary 생성

### ISSUE THREAD

**Issue by winterzzi** [codingpot/pr12er#36]
시즌2~4 까지 고유값 추출

강민국
강지양
김경선
김병학
김성철
김소연
김영석
김태수
김태오
김택민
류성옥
박성남
변윤선
서재덕
유재준
윤진성
이도엽
이윤성
이재원
이준호
이진원
이형민
이호성
전현규
정경훈
정지원
정창훈
주성훈

- 시즌 | 이름 으로 구성, 
Season 2 | 강민국
Season 2 | 김병학
Season 2 | 김태오
Season 2 | 김태수
Season 2 | 김택민
Season 2 | 윤진성
Season 2 | 정지원
Season 2 | 이진원
Season 2 | 김영석
Season 2 | 이재원
Season 2 | 김소연
Season 2 | 서재덕
Season 2 | 주성훈
Season 2 | 이도엽
Season 2 | 박성남
Season 3 | 강지양
Season 3 | 박성남
Season 3 | 주성훈
Season 3 | 류성옥
Season 3 | 김태오
Season 3 | 이도엽
Season 3 | 이진원
Season 3 | 이호성
Season 3 | 김경선
Season 3 | 김영석
Season 3 | 김병학
Season 3 | 정경훈
Season 3 | 정창훈
Season 3 | 이형민
Season 3 | 변윤선
Season 3 | 이윤성
Season 4 | 이도엽
Season 4 | 이형민
Season 4 | 김경선
Season 4 | 이진원
Season 4 | 김성철
Season 4 | 변윤선
Season 4 | 전현규
Season 4 | 이준호
Season 4 | 박성남
Season 4 | 이윤성
Season 4 | 김병학
Season 4 | 유재준
Season 4 | 주성훈

**Comment by kkweon** [comment]
오오 굳입네다. 근데 영어 이름이랑 한글이랑 매칭 수동으로 해야 되는가 OTL

**Comment by winterzzi** [comment]
ㅋㅋㅋㅋㅋㅋ아니 어떻게 구현하시는디용 ㅋㅋㅋㅋ
머 도울거 있으면 제가 ㅋㅋㅋㅋ

**Comment by kkweon** [comment]
현재 메타데이터DB엔 다 영어로 되어 있어서 
한글로 변경해야 될듯합니다.

`Sunghun Kim -> 김성훈`

```
Sunghun Kim
Jiwon Jung
Soyeon Kim
Keunbong Kwak
Jiyang Kang
Ji-Hoon Kim
MinGuk Kang
Yeoung Seok Kim
Jaewon Lee
Taegyun Jeon
Kiho Suh
Seungil Kim
Young Jae Choung
Taesu Kim
KwangHee Lee
Young Seok Kim
Jaejun Yoo
Jinsung Yoon
Jae Duk Seo
Doyeop Lee
Byung-Hak Kim
Dongjun Jung
Taekmin Kim
Sungnam Park
Terry TaeWoong Um
Seongok Ryu
Yeong Seok Kim
Sunghoon Joo
Taeoh Kim
Jinwon Lee
Doyup Lee
Junbum Cha
```

**Comment by winterzzi** [comment]
허허 ㅋㅋㅋㅋ 데이터 받으면 변환해줘야 하는군요
제가 도와드릴 수 있는 부분이 있을까요?

**Comment by kkweon** [comment]
이미 많이 해주셔서 충분함니당

**Comment by winterzzi** [comment]
넹 ㅋㅋ 도울일 있으면 언제든지 말씀해주세요

**Comment by kkweon** [comment]
decided not to do.
