### ISSUE TITLE
Add gRPC middlewares (logging, metrics)

### ISSUE THREAD

**Issue by kkweon** [codingpot/pr12er#37]

**Comment by kkweon** [comment]
https://github.com/grpc-ecosystem/go-grpc-middleware 참고용

**Comment by kkweon** [comment]
logrus와 Prometheus 생각하고 있지만 
다른거 생각하신게 있으시다면 알려주세요.

**Comment by nicewook** [comment]
감사합니다. 눈에 익은 이름입니다. 해보겠습니당

**Comment by nicewook** [comment]
일단 logrus 부터 챙겨보겠습니다.

**Comment by kkweon** [comment]
위 미들웨어 라이브러리만 추가하시고 제대로 작동하는지만 확인해주시면 됩니다.

**Comment by nicewook** [comment]
후다닥 복붙해서 logrus가 gRPC 정보 뿜어내는건 확인했습니다.
프로메테우스는 개념이해중이긴 한데 pull 해가는 프로메테우스 서버가 별도로 필요한건가 개념잡고 있는 중이며 그라파나까지 함께 보다보니 Helm 까지 들어가게 되네요. 

둘 다 어디서 일단 멈춰야 하는지 눈 앞의 목표를 정확히 모르겠습니다. :-)

**Comment by kkweon** [comment]
네 이 이슈는 Prometheus 서버보다는 URL/metrics 에 metrics  이 나오게 하는 것이 목표입니다.
Promethesus 는 그라파나 랩 무료버전으로 돌릴 예정

**Comment by kkweon** [comment]
[중요 포인트]

- 로그에 나오는 정보들이 충분/적절한가
- 적절한 metrics 들이 이미 정의되있는가? 아니라면 정의 필요

**Comment by nicewook** [comment]
완벽하게 하기보다 일단 되게 올려둬야겠군요.

**Comment by nicewook** [comment]
둘 다 거기까진 확인했습니다

**Comment by kkweon** [comment]
가장 중요한 histogram latency가 빠졌네요 왜지..

**Comment by kkweon** [comment]
아래가 있음에도 불구하고 
histogram variable 이 왜 빠졌는지 모르겠습니다.


```go
	grpc_prometheus.EnableHandlingTimeHistogram()
```

**Comment by kkweon** [comment]
알아냈습니다

**Comment by kkweon** [comment]
Fixed in https://github.com/codingpot/pr12er/commit/f35c14abd98a80be2481d3290f05aab6b36dd218
