### ISSUE TITLE
디테일뷰에 필요한 데이터를 가져오는 새로운 RPC 메소드 구현

### ISSUE THREAD

**Issue by deep-diver** [codingpot/pr12er#40]
information that can be acceed via `paperswithcode-go`.
- https://github.com/codingpot/paperswithcode-go

**Comment by kkweon** [comment]
`GetVideos()` 는 List View 에 필요한 데이터를 가져오고
`GetDetails(videoID)` 는 Details View 에 필요한 데이터를 가져온다

**Comment by deep-diver** [comment]
paperswithcode-go 뿐만 아니라 arxiv API도 활용해야함.
