### ISSUE TITLE
Implement GetDetails

### ISSUE THREAD

**Issue by kkweon** [codingpot/pr12er#60]
https://github.com/codingpot/pr12er/blob/081fdd8ac0328c659b14bf94bbf0225185d360b5/server/pkg/pr12er/service.proto#L23

**Comment by nicewook** [comment]
완벽한 response 요구사항까지는 아니지만 어느 정도는 필요한 필드에 대한 정리는 하고 구현하면 더욱 좋겠습니다.

**Comment by kkweon** [comment]
Fixed
