### ISSUE TITLE
[플러터]  즐겨찾기 기능 구현

### ISSUE THREAD

**Issue by winterzzi** [codingpot/pr12er#82]
즐겨찾기 기능
1. 위에 핀박아서 고정, 다른 조건으로 검색해도 해당 핀 유지되도록
2. 현재 있는 리스트 화면에서 즐겨찾기 누르면 핀으로 고정 (ex. PR203 영상의 즐겨찾기를 누르면 검색창 밑에 고정되고 이후 검색창에서 GAN 등 다른 키워드로 검색하더라도 해당 즐겨찾기를 누른 영상 밑이 변경, 엑셀 틀고정처럼...)

**Comment by kkweon** [comment]
implemented in #143
