### ISSUE TITLE
video.id should be renamed to video.pr_id

### ISSUE THREAD

**Issue by kkweon** [codingpot/pr12er#88]
https://github.com/codingpot/pr12er/blob/313d68325875213e9b39458eb3396857116abdba/server/pkg/pr12er/messages.proto#L25

because it's confusing

## Context

- https://docs.google.com/document/d/1UE-v0mYirRdBI1kaK00mG2SPqAuYv9b2WLjEXWGDwnU/edit?disco=AAAAML3RC2c

**Comment by deep-diver** [comment]
현재 작업중인 플로터 코드를 픽스한 후 작업하겠습니다.

**Comment by kkweon** [comment]
작은 pr 고고
